---
title: Confex UK | Continuous Rotary Extrusion Specialists
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Confex UK
  logo_img: "/images/Confex2b.png"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: images/logo_alt.png
  tagline: SaaS theme by Stackbit
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Stackbit. All rights reserved."
  links:
  - text: 'Design By #esc'
    url: http://eaglesoftware.tech
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
